import streamlit as st
import numpy as np
from PIL import Image
import onnxruntime as ort
from datetime import datetime

import google.generativeai as genai
from fpdf import FPDF
import tempfile
import os
from datetime import date

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Image as RLImage
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.colors import grey

st.set_page_config(page_title="Diabetic Retinopathy Classifier", layout="wide")

genai.configure(api_key=st.secrets["GEMINI_API_KEY"])

model = genai.GenerativeModel(model_name="gemini-2.0-flash")

if "user_info" not in st.session_state:
    st.session_state.user_info = {
        "name": "",
        "age": None,
        "gender": "",
        "dob": None,
        "image_path": None
    }

def generate_report_text(predicted_class, confidence, stage_prob):
    info = st.session_state.user_info
    prompt = f"""
    You are VNIT MedAssistant! Introduce yourself first. 

    Create a short and personalized diagnostic report for a diabetic retinopathy screening.
    The predicted stage is: {predicted_class}, with a model confidence of {confidence:.2f}%. 
    Base your report on the probabilities for different stages: {stage_prob}. 

    Patient Name: {info['name']}, Age: {info['age']}, Gender: {info['gender']}.

    Explain the implications of this stage to a non-medical person, suggest next medical steps,
    and emphasize the importance of regular eye exams. Make it clear, compassionate, and supportive.

    """
    response = model.generate_content(prompt)
    return response.text

def add_watermark(canvas, doc):
    canvas.saveState()
    canvas.translate(A4[0] / 2, A4[1] / 2)
    canvas.rotate(45)
    canvas.setFont('Helvetica-Bold', 36)
    canvas.setFillColor(grey, alpha=0.2)
    canvas.drawCentredString(0, 0, "Generated by VNIT MedAssistant AI")
    canvas.restoreState()

    canvas.saveState()
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(grey)
    footer_text = "Disclaimer: This report is AI-generated and for reference purpose only. Please consult with an Ophthalmologist for a comprehensive evaluation and personalized treatment plan."
    canvas.drawCentredString(A4[0] / 2, 0.5 * inch, footer_text)
    canvas.restoreState()

def create_pdf3(report_text, predicted_class, dr_image_path, face_image_path):
    pdf_path = f"DR_Report_{predicted_class}.pdf"
    doc = SimpleDocTemplate(pdf_path, pagesize=A4, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=72)

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="SectionHeader", fontSize=14, leading=18, spaceAfter=12, spaceBefore=12, fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="NormalJustified", alignment=TA_JUSTIFY, fontSize=11, leading=16))

    flowables = []
    flowables.append(Paragraph("<b>🩺 Diabetic Retinopathy Report</b>", styles["Title"]))
    flowables.append(Spacer(1, 12))

    if face_image_path:
        img1 = RLImage(face_image_path, width=2*inch, height=2*inch)
        img1.hAlign = 'CENTER'
        flowables.append(img1)
        flowables.append(Spacer(1, 12))

    img2 = RLImage(dr_image_path, width=4*inch, height=4*inch)
    img2.hAlign = 'CENTER'
    flowables.append(img2)
    flowables.append(Spacer(1, 12))

    for paragraph in report_text.strip().split("\n\n"):
        flowables.append(Paragraph(paragraph.replace("\n", "<br/>"), styles["NormalJustified"]))
        flowables.append(Spacer(1, 8))

    doc.build(flowables, onFirstPage=add_watermark, onLaterPages=add_watermark)
    return pdf_path


def create_pdf4(report_text, predicted_class, image_path):
    pdf_path = f"DR_Report_{predicted_class}.pdf"
    doc = SimpleDocTemplate(pdf_path, pagesize=A4,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=72)

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="SectionHeader", fontSize=14, leading=18, spaceAfter=12, spaceBefore=12, fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="NormalJustified", alignment=TA_JUSTIFY, fontSize=11, leading=16))

    flowables = []

    # Title
    title = Paragraph("🩺 <b>Diabetic Retinopathy Report</b>", styles["Title"])
    flowables.append(title)
    flowables.append(Spacer(1, 12))

    # Centered image
    img = RLImage(image_path, width=4 * inch, height=4 * inch)
    img.hAlign = 'CENTER'
    flowables.append(img)
    flowables.append(Spacer(1, 12))

    # Add report text
    for paragraph in report_text.strip().split("\n\n"):
        if paragraph.strip().startswith("**") and "**" in paragraph.strip()[2:]:
            header_text = paragraph.strip().replace("**", "")
            flowables.append(Paragraph(header_text, styles["SectionHeader"]))
        else:
            flowables.append(Paragraph(paragraph.replace("\n", "<br/>"), styles["NormalJustified"]))
        flowables.append(Spacer(1, 8))

    # Build with watermark and footer on every page
    doc.build(flowables, onFirstPage=add_watermark, onLaterPages=add_watermark)

    return pdf_path

@st.cache_resource
def load_onnx_model():
    session = ort.InferenceSession("mlmodel.onnx")
    input_name = session.get_inputs()[0].name
    input_shape = session.get_inputs()[0].shape
    return session, input_name, input_shape

session, input_name, input_shape = load_onnx_model()
class_labels = ['No DR', 'Mild', 'Moderate', 'Severe', 'Proliferative DR']

tab1, tab2, tab3, tab4, tab5 = st.tabs(["👤 User Info", "📷 Classify Image",  "📚 DR Stages", "📊 Model Info", "👨‍⚕️ About Me"])

with tab1:
    st.header("👤 Enter User Information")
    st.session_state.user_info["name"] = st.text_input("Full Name")
    st.session_state.user_info["gender"] = st.selectbox("Gender", ["Select", "Male", "Female", "Other"])
    age_option = st.radio("Provide: ", ["Date of Birth", "Age"])

    if age_option == "Date of Birth":
        dob = st.date_input("Date of Birth", value=date.today(), min_value=date(1900, 1, 1), max_value=date.today())
        
        today = date.today()
        age = str(today.year - dob.year) + "yrs"#- ((today.month, today.day) < (dob.month, dob.day))

        st.session_state.user_info["age"] = age
    else:
        age = st.number_input("Age (in years)", min_value=1, max_value=120)
        st.session_state.user_info["age"] = str(int(age))+'yrs'
        #st.session_state.user_info["dob"] = None

with tab2:
    st.header("📷 Upload Fundus Image")
    uploaded_file = st.file_uploader("Upload Fundus Image", type=["jpg", "jpeg", "png"])
    if uploaded_file:
        image = Image.open(uploaded_file).convert("RGB")
        st.image(image, caption="Uploaded Image", use_column_width=True)
        target_size = tuple(input_shape[1:3])
        image = image.resize(target_size)
        img_array = np.array(image).astype(np.float32) / 255.0
        img_array = np.expand_dims(img_array, axis=0)

        try:
            prediction = session.run(None, {input_name: img_array})[0][0]
            predicted_class = class_labels[np.argmax(prediction)]
            confidence = np.max(prediction) * 100
            stage_prob = {label: float(prob) for label, prob in zip(class_labels, prediction)}

            st.markdown(f"### 🧠 Prediction: `{predicted_class}`")
            st.markdown(f"### 📈 Confidence: `{confidence:.2f}%`")
            st.markdown("#### 🔍 Full Prediction Probabilities:")
            st.bar_chart(stage_prob)

            if st.button("📝 Generate Report PDF"):
                with st.spinner("Generating report..."):
                    temp_image_path = "temp_fundus.png"
                    image.save(temp_image_path)
                    face_image_path = st.session_state.user_info.get("image_path", None)
                    report_text = generate_report_text(predicted_class, confidence, stage_prob)
                    pdf_path = create_pdf4(report_text, predicted_class, temp_image_path)
                    with open(pdf_path, "rb") as f:
                        st.download_button("📥 Download PDF Report", f, file_name="DR_Report.pdf", mime="application/pdf")
                    os.remove(pdf_path)
                    os.remove(temp_image_path)
        except Exception as e:
            st.error(f"❌ Model inference failed: {str(e)}")

with tab3:
    st.title("📚 Diabetic Retinopathy Stages")
    stages = {
        "No DR": "No visible damage to the retina.",
        "Mild": "Microaneurysms begin to appear.",
        "Moderate": "Blood vessels in the retina are blocked.",
        "Severe": "Many more blood vessels are blocked, retina is damaged.",
        "Proliferative DR": "New abnormal blood vessels grow; risk of vision loss is high."
    }
    for stage, desc in stages.items():
        st.markdown(f"### {stage}")
        st.write(desc)
        st.progress((list(stages.keys()).index(stage) + 1) / len(stages))

with tab4:
    st.title("📊 Model Information")
    st.markdown("""
    - **Model Type**: DenseNet121 (converted to ONNX)
    - **Trained On**: Labeled Indian DR Dataset
    - **Input Size**: 224x224 RGB (normalized float32)
    - **Classes**: No DR, Mild, Moderate, Severe, Proliferative DR
    - **Accuracy Achieved**: ~73%
    - **Inference Engine**: ONNX Runtime (no TensorFlow required!)
    """)

    st.image("https://miro.medium.com/v2/resize:fit:1400/1*ckLNL5fx3JNhgNzKeOnx_w.png", caption="Densenet Architecture")


with tab5:
    st.title("👨‍💻 About This Project")
    st.markdown("""
    This app was created by **Krishang Gupta** as part of a machine learning project to automate the classification of Diabetic Retinopathy using deep learning.

    - 🔬 Based on Densenet121, converted to ONNX
    - 🧠 Inference done using ONNX Runtime (faster + cloud-ready)
    - 🧑‍🏫 Goal: Assist medical professionals in early detection of DR

    [📧 Contact](mailto:krishanggupta.kg@gmail.com) | [🌐 LinkedIn](https://www.linkedin.com/in/krishang-gupta-0b0041305/)
    """)

    st.image("https://upload.wikimedia.org/wikipedia/commons/0/06/Retinopathy3.jpg", caption="Sample DR Image")

    
    
